export const Util: typeof import("./util/Util");
export const Logger: typeof import("./util/Logger");
export const World: typeof import("./structures/World");
export const Server: typeof import("./Server");
export const Events: {
    readonly ServerOpen: "serverOpen";
    readonly ServerClose: "serverClose";
    readonly WorldAdd: "worldAdd";
    readonly WorldRemove: "worldRemove";
    readonly PlayerJoin: "playerJoin";
    readonly PlayerLeave: "playerLeave";
    readonly PacketReceive: "packetReceive";
    readonly Error: "error";
    readonly PlayerChat: "playerChat";
    readonly PlayerTitle: "playerTitle";
    readonly Tick: "tick";
};
export const ScoreboardManager: typeof import("./managers/ScoreboardManager");
export const ScoreboardObjective: typeof import("./structures/ScoreboardObjective");
export * from './types';