export enum ServerEvent {
  Open,
  Close,
  WorldAdd,
  WorldRemove,
  WorldInitialize,
  PlayerJoin,
  PlayerLeave,
  PlayerLoad,
  PlayerChat,
  PlayerTitle,
  PlayerMessage,
  EnableEncryption,
  PlayerTransform,
  PlayerTravelled,
}
