name: Lint
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'
      - uses: pnpm/action-setup@v4
      - run: pnpm i --frozen-lockfile
      - name: Lint
        run: pnpm run lint
